POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc0MzEwMzQzMCwidXNlcklkIjoyfQ.Ww02ErpOqaRqwdI9SsOjMCuRWOFIvqQ5AipcMtdIbvs

{
    "name":"Old age home3",
    "description":"old age home for old people3",
    "location" : "saraswati vihar, kolkata",
    "dateTime" : "2025-01-01T15:00:10.000Z" 
}